### ISSUE TITLE
Can't easily scroll entire page when viewing multiple long lists

### ISSUE THREAD

**Issue by emertechie** [sudonatalie/layout-trello#18]
Hey. Love the extension. One minor issue I have is when viewing a many long lists in the "grid" view, I may want to scroll down the page but as soon as the cursor hits a Trello list box, it starts scrolling that list instead of the page.

Is it possible to not scroll Trello lists if the shift key is held down?

**Comment by natalieperna** [comment]
This is an interesting suggestion. I'm not sure how to go about doing it, but I'm sure it's possible.

If you happen to be able to create the patch yourself, I'd be happy to integrate it into the extension. Otherwise, I'll leave the issue open and try it myself some time.

**Comment by spellitwithaph** [comment]
@emertechie, have a look at my [fork](https://github.com/spellitwithaph/layout-trello), I've taken a shot at implementing this feature. The shift key seems to be a blocker with my mouse's scroll wheel but does work with my macbook's trackpad. 

I'm not sure this should be added without a configuration setting so I didn't do a pull request.

**Comment by natalieperna** [comment]
@spellitwithaph, go ahead and make a PR to the new branch [issue-18](https://github.com/natalieperna/layout-trello/tree/issue-18) if it's working for you, even if only partially. I'll see if I can iron out any kinks and merge with master. I don't think it needs to be behind a settings page if it's a feature that only occurs when some control key is held down.

**Comment by sudonatalie** [comment]
No longer considering this feature.
