### ISSUE TITLE
[request] In the Vertical List, make cards wider

### ISSUE THREAD

**Issue by iurikothe** [sudonatalie/layout-trello#21]
When listing vertically, use the whole width of the page.
So it looks similar to Redmines Roadmap page:
http://www.redmine.org/projects/redmine/roadmap

<img width="1255" alt="screen shot 2016-07-01 at 11 19 56 copy" src="https://cloud.githubusercontent.com/assets/161468/16524367/53c54f1a-3f7e-11e6-8954-f45cb56f578c.png">

Other suggestions: 
- smaller font and 
- collapsing lists (toggle: shows first 5 cards or all)

this is interesting for boards with many lists and cards (with long titles) so one has a nice overview of everything at once

thanks

**Comment by natalieperna** [comment]
> When listing vertically, use the whole width of the page.

I'd be inclined to add this if/when I get around to adding an Options page to the extension for customizations.

In the meantime, you might consider using an extension like [Styler](https://chrome.google.com/webstore/detail/styler/bogdgcfoocbajfkjjolkmcdcnnellpkb?hl=en) to add custom CSS to the page. I think something like this would do what you're looking for:

```
#board.layout-trello-vertical .list-wrapper {
    width: 100%;
}

.list-card {
    max-width: 100%;
}
```

> Other suggestions:
> smaller font and

Smaller font probably strays too far from the narrow purpose of the extension. 

> collapsing lists (toggle: shows first 5 cards or all)

Collapsing lists would require more complexity than I want to introduce.

**Comment by iurikothe** [comment]
awesome, thanks!

**Comment by iurikothe** [comment]
This setting worked lovely for me:

```
#board.layout-trello-vertical .list-wrapper {
    width: 95%;
}

#board.layout-trello-vertical .list-card {
    max-width: 99%;
}
```

**Comment by sudonatalie** [comment]
No longer considering this feature.
