### ISSUE TITLE
[Request] Masonry Card List?

### ISSUE THREAD

**Issue by grpace** [sudonatalie/layout-trello#23]
Maybe it would defeat the purpose of Trello but I think it would look really nice to have an option to make the cards fit into place and remove whitespace from list where some are longer than others. Just an suggestion for future releases.

**Comment by natalieperna** [comment]
I looked into this in the past and couldn't figure out an easy way to implement it, even with the masonry framework. I'm no expert with CSS though, so if anyone else was willing to put the work into making this happen I'd definitely accept a PR...

**Comment by sudonatalie** [comment]
No longer considering this feature.
