### ISSUE TITLE
Request:  Custom Grid Layout

### ISSUE THREAD

**Issue by tyrynt** [sudonatalie/layout-trello#24]
Hi,

I would like to second the comment/request that Gary Newton made on the review section of the chrome store.

It would be great to be able to customize the grid layout.  For example a 2x2 grid would cleanly facilitate an Eisenhower Box decision process.

Thank you for a great app.

**Comment by natalieperna** [comment]
I'll probably add an Options page in a future version, and would consider including this then.

**Comment by tyrynt** [comment]
Thank you for the reply.

Trevor

**Comment by jadeclan** [comment]
Love the app.  Great work.  I would like to second the idea of have customization for grids.  In my particular case, my flow looks a bit like a black diamond ski hill (high on left, with next to nada just before completion of an item). Sooo, being able to have column layouts that might look like 1, 1, 1, 2, 1 where the 2 would be stacked vertical showing 2 lists - (so 5 columns, with one of the columns containing 2 lists....alternatively (not as flexible), it could be a 2 row by 5 columns with the second row only having material in the 4th column).

**Comment by mjohenneken** [comment]
I like the idea of having a customizable grid. Currently i have some lists which are logically 2 and i divide them with a card with title "--------". But if you use something like card altering or i move a card to the list it's a mess.

I would recommend stackable lists, so that each column of the grid can have multiple lists. This would also  solve the 2 previous use cases.

**Comment by nocibambi** [comment]
My simple custom grid idea for two-week sprint planning: two five-list rows would for each day in the sprint.

**Comment by sudonatalie** [comment]
Closing this issue as I'm no longer considering this feature. Unfortunately I think it just adds too much additional complexity to what is currently a very simple extension.
