### ISSUE TITLE
List Layouts doesn't work

### ISSUE THREAD

**Issue by leahmtc** [sudonatalie/layout-trello#36]
Hi, I've added the Chrome extension and the icon is greyed out. When I click on it nothing happens. I'm using Chrome Version 62.0.3202.75 on macOS Sierra.

**Comment by sudonatalie** [comment]
Not really sure what's causing this, but I've seen a few reports of it and haven't been able to reproduce it yet.

**Comment by REIDesignSolutions** [comment]
I am having that issue as well.  I have tried logging out of Chrome and Trello and logging back in again to no avail.  Any info?

**Comment by sudonatalie** [comment]
I'm not really sure what's causing this, but a few people have reported the issue resolving itself after a couple days. It seems like an issue with the Chrome Web store installer, but I don't have enough information to figure out why.

**Comment by REIDesignSolutions** [comment]
Thanks for taking the time to let me know...same happened here.  It is now
working! Great hack, thanks!


*Christine Heartsill*   Owner | Principle Designer
[image: photo] Phone: 713-984-8097
Email: christine@reidesignsolutions.com
Website: REIdesignsolutions.com
<http://www.facebook.com/REIdesignsolutions/?ref=aymt_homepage_panel>
<http://www.linkedin.com/in/christine-heartsill-161372107>
<http://www.pinterest.com/reidesignsolutions>
Turnkey design solutions for Real Estate investors.
<https://www.facebook.com/10205050407574749>
<https://www.facebook.com/1924096930949192_2509884552370424> REI Design
Solutions completely pioneered a business catered to helping real estate
investors, through far more than coa...
REI Design Solutions <https://www.facebook.com/1924096930949192>
<https://www.facebook.com/10205050407574749>
<https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2F1924096930949192_2509884552370424>

On Mon, Jun 25, 2018 at 8:53 PM, Natalie Chouinard <notifications@github.com
