### ISSUE TITLE
Cant get Layouts to work

### ISSUE THREAD

**Issue by JamieJ1** [sudonatalie/layout-trello#44]
Hi. I've installed this extension but when I click on the Extension button (whilst on a Trello board), nothing happens, the ext just gives me the options; "List Layouts For Trello" - takes me to the Chrome Extension page, "Remove Extension," etc. 

Also when using this extension and putting lists on top of each other in Grid view, is it possible to collapse lists vertically so that I can get an easy overview of all my Lists titles?

**Comment by sudonatalie** [comment]
I'm not sure why clicking the extension icon is bringing up the context menu rather than changing the board layout. Usually that menu is only brought up when you right-click.

This extension doesn't support collapsing lists.

**Comment by JamieJ1** [comment]
Thanks sudonatalie. This button seems to be working now. Do you happen to know of any other extension or powerups that provide for collapsing lists?
