### ISSUE TITLE
Moving lists manually around the grid

### ISSUE THREAD

**Issue by JamieJ1** [sudonatalie/layout-trello#46]
So I want to try and create a layout similar to the below screenshot and be able to drag & drop the lists wherever I like rather than them being automatically sorted from left to right (because I want my Projects to line up vertically under each of my Areas). Would it be possible to request this as a feature?

<img width="1435" alt="areas projects layout - trello" src="https://user-images.githubusercontent.com/16798009/41017481-e8b1c46a-694c-11e8-8206-aa8fe087d9cc.png">

**Comment by JamieJ1** [comment]
Bump

**Comment by sudonatalie** [comment]
Please don't bump issues.

Changing the sorting order of lists is outside of the fairly narrow scope of this extension.
