### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by quadsurf** [sudonatalie/layout-trello#47]
clicking the extension's icon does nothing in chrome (@latest version)... icon is disabled when trello is not detected (expected)... refreshing tab causes icon to detect trello and then it auto-switches to enabled (expected), but then when i click the icon when it's in its enabled state, nothing happens (not expected)... my lists do not toggle between horizontal view, grid view (rows), and vertical view. please help

**Comment by sudonatalie** [comment]
Not sure why this happens sometimes. Most people that have reported it say that it starts working on it's own within a few hours to a day. Seems to be some issue with the Chrome Web store installation that I can't reproduce.
