### ISSUE TITLE
Grid Layout view is not working for Chrome

### ISSUE THREAD

**Issue by suyashjain** [sudonatalie/layout-trello#48]
Hi,

This is an awesome extension, but unfortunately I am not able to set the grid view (multiple column and multiple row) like the one mentioned in this screen shot.
![image](https://user-images.githubusercontent.com/3862495/46391345-128aa580-c6fa-11e8-8701-f07b1538b95f.png).

When I click on button, it either go vertically or horizontally in single line.

Thanks in advance

**Comment by sudonatalie** [comment]
The "grid" layout works by wrapping lists that would extend past the right edge onto the next row. If you don't have enough lists that they need to be wrapped around, then grid and horizontal will look the same.

**Comment by elizabethswkim** [comment]
Feature request: Vertically and horizontally arrange lists (not just wrapping when they overflow past the right edge, but vertically stacking by choice, in addition to horizontal layout). In my today column, I want to split into multiple lists (ie, ongoing and emergent in the same column but in separate lists).
