### ISSUE TITLE
Left arrow not working in cards with extension enabled

### ISSUE THREAD

**Issue by viralk** [sudonatalie/layout-trello#50]
Hello, I came here after replying to this discussion on the Atlassian Community:
[Left arrow key not working within cards](https://community.atlassian.com/t5/Trello-questions/Left-arrow-key-not-working-within-cards/qaq-p/1032518#M12780)

After some testing It seems that when the extension is active on chrome 73.0.3683.75 the left arrow key is not working. Disabling the extension restores the normal behaviour.

Inpecting the page with the extension active result in the following error:
Error handling response: TypeError: Cannot read property 'classList' of null
in the file: setup.css.js:21:11

**Comment by sudonatalie** [comment]
@viralk Did you close this issue because you're no longer seeing the error or do you want to re-open it?

**Comment by viralk** [comment]
The Atlassian team released a fix for this problem yesterday, the console error i was getting from the extension was not related to the left arrow not working.
