### ISSUE TITLE
How to implement this extension?

### ISSUE THREAD

**Issue by fernandafooks** [sudonatalie/layout-trello#55]
Hi there, I downloaded this extension but I can't figure out how to use it, ie I'm in Trello and I still don't see how I can stack cards vertically. Can you please tell me how to do so? Thanks! :)

**Comment by cahardbarger** [comment]
I have the same problem.  Please help!

**Comment by sudonatalie** [comment]
When you're on a Trello board page, there should be a blue and white square icon to the right of the address bar. Clicking on it will alternate through the 3 layout options. If you have many extensions installed, you may need to click the 3-dots menu in the top-right corner of your browser to see it.
