### ISSUE TITLE
Horizontal, or row layout does not initiate

### ISSUE THREAD

**Issue by marmeesewing** [sudonatalie/layout-trello#56]
**I am using List Layouts For Trello in Chrome (Version 77.0.3865.120 (Official Build) (64-bit), OS Windows 10  Home**
____
When I click the icon for List Layouts I get three different card/list lengths, but neither of the two horizontal, or row layouts.

Am I missing something?  Please fix this issue.

**Comment by marmeesewing** [comment]
I love the options your extension adds to Trello and cannot see myself working without it, but only if the vertical-to-horizontal layout functionality works cleanly.

**Comment by Scrimpie** [comment]
Sorry if this is too obvious, but did you try restarting the browser? I had the same trouble, came looking here, and saw your post. Then, I thought, since I had just installed the extension, maybe it needs a browser restart. So I closed and reopened, and it works great now.

**Comment by sudonatalie** [comment]
@marmeesewing I don't quite understand the issue you're describing. Can you provide a video?
