### ISSUE TITLE
More Space Between horizontal Rows

### ISSUE THREAD

**Issue by Dlafko** [sudonatalie/layout-trello#58]
Hi I just got my employer to add this extension for Trello.. Love it.  Only question I have 2 rows Top and Bottom. My top row lists will be longer than the bottom row. Is there any way to add more space between the rows so That I can see more of a longer list vs having to scroll all the way down. In that card?  Would be a big help if there's a way to do that. 

Thanks Love the extension.

**Comment by sudonatalie** [comment]
Duplicate #13
