### ISSUE TITLE
BOARD GRID VIEW - Horizontal and Vertically Locations

### ISSUE THREAD

**Issue by JTSMOM2005** [sudonatalie/layout-trello#59]
Is there not a way to organize your view of boards and cards? Other than Horizontal or Vertical? Why are the cards nd boards not widgets to be more customizable, someone's else visua organization is not necessarily someone else

**Comment by sudonatalie** [comment]
> Is there not a way to organize your view of boards and cards? Other than Horizontal or Vertical?

This extension supports 3 view layouts for Trello boards: Horizontal, Vertical and Grid.

> Why are the cards nd boards not widgets to be more customizable, someone's else visua organization is not necessarily someone else

I'm not sure what you mean by widgets, or what additional customizability you're looking for, but this is a small extension that likely won't add many new features in future, so it may not serve the purpose you're looking for.
