### ISSUE TITLE
List Layouts for Trello Chrome extension doesn't work

### ISSUE THREAD

**Issue by VirginiaDavisVA** [sudonatalie/layout-trello#61]
I've logged out, logged back in, refreshed about a dozen times...

**Comment by sudonatalie** [comment]
Can you be more specific about the behavior you're seeing? If possible, please include screenshots or a screen recording.

**Comment by VirginiaDavisVA** [comment]
I downloaded the Chrome extension because the Trello board I was on
suggested that it would allow the board to not have to be scrolled over to
the right, but would create new cards within the same screen space.  I saw
an example of it on the board, but it didn't work for me.  This was weeks
ago; I'm not sure if I can find that board again.

**Comment by sudonatalie** [comment]
If you're able to reproduce the error feel free to re-open this issue with more information.
